language: cpp
sudo: required
services:
  - docker
env:
  - GCC_VERSION: 4.6
  - GCC_VERSION: 4.8
  - GCC_VERSION: 4.9
  - GCC_VERSION: 5.2
  - GCC_VERSION: 5.3
install:
  - mkdir -p ~/.conan/data
script:
  - export CONAN_UPLOAD=1 && 
           CONAN_REFERENCE="Boost/1.60.0" && 
           CONAN_USERNAME="lasote" && 
           CONAN_CHANNEL="travis" && 
           python build_with_docker.py $GCC_VERSION