language: cpp
sudo: required
services:
  - docker
env:
  - GCC_VERSION: 4.6
  - GCC_VERSION: 4.8
  - GCC_VERSION: 4.9
  - GCC_VERSION: 5.2
  - GCC_VERSION: 5.3
install:
  - wget http://downloads.conan.io/latest_debian -O conan.deb
  - sudo dpkg -i conan.deb
  - rm conan.deb
  - conan user # It creates the conan data directory
script:
  - export CONAN_UPLOAD=1 && 
           CONAN_REFERENCE="Boost/1.60.0" && 
           CONAN_USERNAME="lasote" && 
           CONAN_CHANNEL="travis" && 
           python build_with_docker.py $GCC_VERSION