build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_REFERENCE: "Boost/1.65.1"
    CONAN_USERNAME: "conan"
    CONAN_LOGIN_USERNAME: "lasote"
    CONAN_CHANNEL: "testing"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
    CONAN_UPLOAD: "https://api.bintray.com/conan/conan-community/conan"
    CONAN_STABLE_BRANCH_PATTERN: "release/*"
    CONAN_TOTAL_PAGES: 4
    CONAN_UPLOAD_ONLY_WHEN_STABLE: 1 # Will only upload when the branch matches "release/*"

    matrix:

        - MINGW_CONFIGURATIONS: "6.3@x86_64@seh@posix"
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
          CONAN_CURRENT_PAGE: 1

        - MINGW_CONFIGURATIONS: "6.3@x86_64@seh@posix"
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
          CONAN_CURRENT_PAGE: 2

        - MINGW_CONFIGURATIONS: "6.3@x86_64@seh@posix"
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
          CONAN_CURRENT_PAGE: 3

        - MINGW_CONFIGURATIONS: "6.3@x86_64@seh@posix"
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
          CONAN_CURRENT_PAGE: 4


        - MINGW_CONFIGURATIONS: "7.1@x86_64@seh@posix"
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
          CONAN_CURRENT_PAGE: 1

        - MINGW_CONFIGURATIONS: "7.1@x86_64@seh@posix"
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
          CONAN_CURRENT_PAGE: 2

        - MINGW_CONFIGURATIONS: "7.1@x86_64@seh@posix"
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
          CONAN_CURRENT_PAGE: 3

        - MINGW_CONFIGURATIONS: "7.1@x86_64@seh@posix"
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
          CONAN_CURRENT_PAGE: 4

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_CURRENT_PAGE: 1
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_CURRENT_PAGE: 2
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_CURRENT_PAGE: 3
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_CURRENT_PAGE: 4

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_CURRENT_PAGE: 1
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_CURRENT_PAGE: 2
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_CURRENT_PAGE: 3
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_CURRENT_PAGE: 4

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
          CONAN_CURRENT_PAGE: 1
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
          CONAN_CURRENT_PAGE: 2
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
          CONAN_CURRENT_PAGE: 3
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
          CONAN_CURRENT_PAGE: 4

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
