build: false

environment:
    PYTHON: "C:\\Python37"
    CONAN_TOTAL_PAGES: 4

    matrix:

        - MINGW_CONFIGURATIONS: "6@x86_64@seh@posix"
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
          CONAN_CURRENT_PAGE: 1
          CONAN_TOTAL_PAGES: 2

        - MINGW_CONFIGURATIONS: "6@x86_64@seh@posix"
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
          CONAN_CURRENT_PAGE: 2
          CONAN_TOTAL_PAGES: 2

        - MINGW_CONFIGURATIONS: "7@x86_64@seh@posix"
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
          CONAN_CURRENT_PAGE: 1
          CONAN_TOTAL_PAGES: 2

        - MINGW_CONFIGURATIONS: "7@x86_64@seh@posix"
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
          CONAN_CURRENT_PAGE: 2
          CONAN_TOTAL_PAGES: 2

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_CURRENT_PAGE: 1
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_CURRENT_PAGE: 2
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_CURRENT_PAGE: 3
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_CURRENT_PAGE: 4

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_CURRENT_PAGE: 1
          CONAN_TOTAL_PAGES: 5
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_CURRENT_PAGE: 2
          CONAN_TOTAL_PAGES: 5
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_CURRENT_PAGE: 3
          CONAN_TOTAL_PAGES: 5
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_CURRENT_PAGE: 4
          CONAN_TOTAL_PAGES: 5
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_CURRENT_PAGE: 5
          CONAN_TOTAL_PAGES: 5

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
          CONAN_CURRENT_PAGE: 1
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
          CONAN_CURRENT_PAGE: 2
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
          CONAN_CURRENT_PAGE: 3
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
          CONAN_CURRENT_PAGE: 4

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
